"""Definição da tabela de usuário e de barbeiros

Revision ID: 11f181b72739
Revises: 
Create Date: 2021-09-02 18:26:28.985700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f181b72739'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbeiro',
    sa.Column('id_barbeiro', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id_barbeiro')
    )
    op.create_index(op.f('ix_barbeiro_email'), 'barbeiro', ['email'], unique=True)
    op.create_index(op.f('ix_barbeiro_nome'), 'barbeiro', ['nome'], unique=False)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_nome'), 'usuario', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_nome'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_barbeiro_nome'), table_name='barbeiro')
    op.drop_index(op.f('ix_barbeiro_email'), table_name='barbeiro')
    op.drop_table('barbeiro')
    # ### end Alembic commands ###
