"""adicionando campo de status da conta

Revision ID: 27482a2867cd
Revises: 88c0107ac40a
Create Date: 2021-11-16 19:42:56.004580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27482a2867cd'
down_revision = '88c0107ac40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbeiro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_bloqueio', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbeiro', schema=None) as batch_op:
        batch_op.drop_column('status_bloqueio')

    # ### end Alembic commands ###
