"""servico

Revision ID: 8433dad5df3b
Revises: 88ef3bf125b7
Create Date: 2021-09-07 13:37:23.436104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8433dad5df3b'
down_revision = '88ef3bf125b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servico',
    sa.Column('id_servico', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_servico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servico')
    # ### end Alembic commands ###
