"""reserva

Revision ID: 88c0107ac40a
Revises: 8433dad5df3b
Create Date: 2021-09-07 13:37:54.732687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c0107ac40a'
down_revision = '8433dad5df3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=True),
    sa.Column('horario_fim', sa.Time(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('barbeiro_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiro.id_barbeiro'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id_servico'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    # ### end Alembic commands ###
