"""barbeiro

Revision ID: 88ef3bf125b7
Revises: 6a4123408f36
Create Date: 2021-09-07 13:36:57.786166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ef3bf125b7'
down_revision = '6a4123408f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbeiro',
    sa.Column('id_barbeiro', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id_barbeiro')
    )
    with op.batch_alter_table('barbeiro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barbeiro_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_barbeiro_nome'), ['nome'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbeiro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barbeiro_nome'))
        batch_op.drop_index(batch_op.f('ix_barbeiro_email'))

    op.drop_table('barbeiro')
    # ### end Alembic commands ###
