"""Banco de dados

Revision ID: bdbfda975a2b
Revises: 
Create Date: 2021-09-05 18:10:54.919751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbfda975a2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbeiro',
    sa.Column('id_barbeiro', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id_barbeiro')
    )
    with op.batch_alter_table('barbeiro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barbeiro_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_barbeiro_nome'), ['nome'], unique=False)

    op.create_table('servico',
    sa.Column('id_servico', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_servico')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_nome'), ['nome'], unique=False)

    op.create_table('reserva',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=True),
    sa.Column('horario_fim', sa.Time(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('barbeiro_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiro.id_barbeiro'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id_servico'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_nome'))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    op.drop_table('servico')
    with op.batch_alter_table('barbeiro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barbeiro_nome'))
        batch_op.drop_index(batch_op.f('ix_barbeiro_email'))

    op.drop_table('barbeiro')
    # ### end Alembic commands ###
